version: "2"
linters:
  enable:
    - misspell
    - modernize
    - revive
    - sloglint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/prometheus-community/fortigate_exporter)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/prometheus-community/fortigate_exporter
